name: Download PubChem Data

on:
  # Manual trigger
  workflow_dispatch:
  
  # Automatic trigger - runs every 6 hours
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write
  actions: read

jobs:
  download:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # Just under 6 hour GitHub limit
    
    steps:
    # 1. Checkout repository
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    # 2. Set up Python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # 3. Install dependencies
    - name: Install requirements
      run: |
        pip install requests
    
    # 4. Restore previous data from cache
    - name: Restore cached data
      uses: actions/cache@v3
      with:
        path: |
          pubchem_downloads/
          progress.json
        key: pubchem-data-${{ github.run_number }}
        restore-keys: |
          pubchem-data-
    
    # 5. Run the downloader
    - name: Download PubChem compounds
      run: python download_pubchem.py
    
    # 5b. Debug - Check what files exist
    - name: Check downloaded files
      run: |
        echo "=== Current directory ==="
        ls -la
        echo "=== Checking for downloads ==="
        if [ -d "pubchem_downloads" ]; then
          echo "Found pubchem_downloads directory"
          echo "Number of files: $(find pubchem_downloads -name "*.json" | wc -l)"
        else
          echo "No pubchem_downloads directory found"
        fi
        if [ -f "progress.json" ]; then
          echo "=== Progress file ==="
          cat progress.json
        else
          echo "No progress.json found"
        fi
    
    # 6. Save data to cache for next run
    - name: Save data to cache
      uses: actions/cache@v3
      with:
        path: |
          pubchem_downloads/
          progress.json
        key: pubchem-data-${{ github.run_number }}
    
    # 7. Also upload as artifact for download
    - name: Upload data as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pubchem-data-run-${{ github.run_number }}
        path: |
          pubchem_downloads/
          progress.json
        retention-days: 90
        if-no-files-found: warn
